version: "3.0"
services:
  db:
    image: "postgres"
    restart: always
    # environment:
      # - POSTGRES_PASSWORD=user
      # - POSTGRES_USER=pw
    expose:
      - 5432
    ports:
      - 5432:5432
    # command: ["postgres"]
  server:
    build: ./backend
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000
  static:
    build: ./frontend
    restart: always
    expose:
      - 80
    ports: 
      - 8080:80