version: "3.0"
services:
  db:
    restart: always
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: 'pw'
      POSTGRES_USER: 'user'
    ports:
      - '5432:5432'
    expose:
      - 5432
    hostname: db

